// <auto-generated />
namespace HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class doctordetail_departmentDbo_Haroon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctordetail_departmentDbo_Haroon));
        
        string IMigrationMetadata.Id
        {
            get { return "202108241122039_doctordetail_departmentDbo_Haroon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
